### PR TITLE
Fix Web Canvas Release On Flutter 3.10

### PR DESCRIPTION
**Pull request by azkadev**
Before:

Screenshot from 2023-05-12 19-54-06

After: 
Screenshot from 2023-05-12 21-28-38
Screenshot from 2023-05-12 21-21-26

### CODE REVIEW

**Comment by payam-zahedi** [comment]
@azkadev 
its not working on the `html` web renderer

image

**Comment by azkadev** [comment]
> @azkadev its not working on the `html` web renderer
> 
> image

from the start this package does not support flutter html web

 #6

**Comment by redDwarf03** [comment]
hello @luisDanielRoviraContreras , could you consider please this PR to publish a new version on pub.dev 🙏🏼
Thank you

**Comment by payam-zahedi** [comment]
@redDwarf03 

you can use this instead

https://github.com/PersianFlutter/iconsax_flutter

**Pull request closed without merging**
